feat(build): use `buildDockerAndPublishImage`
jenkins-infra/plugin-site-api pull request #142
Opened 2023-11-08 14:27 UTC by lemeurherve

This PR uses `buildDockerAndPublishImage` from the shared pipeline library to build and publish the Docker image.

2023-11-08 16:02 UTC, dduportal requested changes
I'm confused: I though this image was currently being deployed by trusted.ci, but the PR shifts it to use infra.ci => which one should we use as target for this PR?

I'm asking because we never used the `buildDockerAndPublishImage` on trusted.ci which might not have the proper credentials or settings to allow it to work as expected.

2023-11-08 16:02 UTC, dduportal commented on Jenkinsfile
> +                echo "No tag for this commit, creating a docker image with ${shortCommit} version..."
This line should be indented (inside an `if` block)

2023-11-08 16:02 UTC, dduportal commented on Jenkinsfile
> +                dockerImage = "jenkinsciinfra/plugin-site-api:${env.BUILD_ID}-${shortCommit}"
This line should be indented (inside an `if` block)

2023-11-08 16:02 UTC, dduportal commented on Jenkinsfile
> +                dockerImage = "jenkinsciinfra/plugin-site-api:${tag}"
These lines should be indented (inside an `if` block)

2023-11-08 16:14 UTC, lemeurherve commented
> I'm confused: I though this image was currently being deployed by trusted.ci, but the PR shifts it to use infra.ci => which one should we use as target for this PR?
> 
> I'm asking because we never used the `buildDockerAndPublishImage` on trusted.ci which might not have the proper credentials or settings to allow it to work as expected.

As there is no private data needed or generated by this build, the target would be infra.ci.jenkins.io

I'll develop the migration plan in https://github.com/jenkins-infra/helpdesk/issues/3619

2023-11-10 11:03 UTC, lemeurherve commented on Jenkinsfile
> +            buildDockerAndPublishImage('plugin-site-api', [unstash: 'build', targetplatforms: 'linux/amd64'])
```suggestion
            buildDockerAndPublishImage('plugin-site-api', [unstash: 'build', enablePublication: infra.isInfra(),targetplatforms: 'linux/amd64'])
```
Publish only on infra.ci.jenkins.io by setting `enabledPublication` to false if not on infra.
Needs https://github.com/jenkins-infra/pipeline-library/pull/784

2023-11-13 13:01 UTC, lemeurherve commented
> I'm confused: I though this image was currently being deployed by trusted.ci, but the PR shifts it to use infra.ci => which one should we use as target for this PR?

As detailed in https://github.com/jenkins-infra/helpdesk/issues/3619#issuecomment-1805437441 the final target is infra.ci.jenkins.io

> I'm asking because we never used the `buildDockerAndPublishImage` on trusted.ci which might not have the proper credentials or settings to allow it to work as expected.

For now `buildDockerAndPublishImage` is executed only on infra.ci.jenkins.io. When this PR will be merged and a first image from infra.ci.jenkins.io validated, I'll remove the job from trusted.ci.jenkins.io.

Then, when https://github.com/jenkins-infra/pipeline-library/pull/784 will be merged, I intent to make `buildDockerAndPublishImage` also run on ci.jenkins.io but with publication disabled.

2023-11-13 13:30 UTC, dduportal approved these changes
A comment (not blocking) which may be addressed later

2023-11-13 14:07 UTC, dduportal approved these changes

2023-11-13 15:22 UTC, merged